import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const gameStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a1628',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#1a3a5c',
  },
  teamInfo: {},
  teamName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
  },
  gameDate: {
    fontSize: 12,
    color: '#6a8aaa',
    marginTop: 2,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 12,
  },
  saveButton: {
    padding: 8,
  },
  content: {
    flex: 1,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#0d2137',
    borderTopWidth: 1,
    borderTopColor: '#1a3a5c',
    paddingBottom: 4,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 2,
  },
  tabButtonActive: {},
  tabLabel: {
    fontSize: 8,
    color: '#4a6a8a',
    marginTop: 2,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: '#00ff88',
  },
  tabContent: {
    flex: 1,
    padding: 12,
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6a8aaa',
    letterSpacing: 1,
    marginBottom: 8,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#0d2137',
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#1a4a6c',
    alignItems: 'center',
  },
  statValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#00ff88',
  },
  statLabel: {
    fontSize: 9,
    color: '#6a8aaa',
    marginTop: 2,
  },
  matchCard: {
    backgroundColor: '#0d2137',
    padding: 14,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#1a4a6c',
    alignItems: 'center',
  },
  matchTeams: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  matchTeam: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9ab8d8',
    flex: 1,
    textAlign: 'center',
  },
  matchTeamHighlight: {
    color: '#00ff88',
  },
  matchVs: {
    fontSize: 12,
    color: '#4a6a8a',
  },
  matchWeek: {
    fontSize: 11,
    color: '#4a6a8a',
    marginTop: 8,
  },
  playButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#00ff88',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 6,
    gap: 6,
    marginTop: 12,
  },
  playButtonText: {
    color: '#0a1628',
    fontSize: 13,
    fontWeight: '800',
  },
  noMatchText: {
    color: '#6a8aaa',
    fontSize: 14,
  },
  
  // ============================================
  // EVENT CARD STYLES (v2 Calendar System)
  // ============================================
  currentDateBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 6,
    marginBottom: 12,
    backgroundColor: '#0d2137',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#1a4a6c',
  },
  currentDateText: {
    color: '#4a9eff',
    fontSize: 11,
    fontWeight: '600',
  },
  eventCard: {
    backgroundColor: '#0d2137',
    padding: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#1a4a6c',
    marginBottom: 8,
  },
  eventCardNext: {
    borderColor: '#00ff88',
    borderWidth: 2,
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  eventDateBadge: {
    backgroundColor: '#1a3a5c',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  eventDateText: {
    color: '#9ab8d8',
    fontSize: 11,
    fontWeight: '600',
  },
  eventTypeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  eventTypeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  eventMatchInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  eventTeamName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9ab8d8',
    flex: 1,
    textAlign: 'center',
  },
  eventTeamHighlight: {
    color: '#00ff88',
    fontWeight: '700',
  },
  eventVs: {
    fontSize: 11,
    color: '#4a6a8a',
    fontWeight: '600',
  },
  eventDrawInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  eventDrawText: {
    color: '#9ab8d8',
    fontSize: 14,
    fontWeight: '600',
  },
  eventTransferInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  eventTransferText: {
    color: '#9ab8d8',
    fontSize: 14,
    fontWeight: '600',
  },
  
  tablePreview: {
    backgroundColor: '#0d2137',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#1a4a6c',
    overflow: 'hidden',
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#1a3a5c',
  },
  tableRowHighlight: {
    backgroundColor: '#1a4a3c',
  },
  tablePos: {
    width: 22,
    fontSize: 11,
    color: '#6a8aaa',
    fontWeight: '700',
  },
  tableTeam: {
    flex: 1,
    fontSize: 11,
    color: '#fff',
  },
  tablePts: {
    width: 28,
    fontSize: 11,
    color: '#00ff88',
    fontWeight: '700',
    textAlign: 'right',
  },
  positionGroup: {
    marginBottom: 14,
  },
  positionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  positionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4a9eff',
    letterSpacing: 1,
  },
  positionCount: {
    fontSize: 11,
    color: '#4a6a8a',
  },
  playerCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#0d2137',
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#1a4a6c',
    marginBottom: 4,
  },
  playerInfo: {
    flex: 1,
  },
  playerName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  playerMeta: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 1,
  },
  playerAge: {
    fontSize: 10,
    color: '#6a8aaa',
  },
  playerNat: {
    fontSize: 10,
    color: '#6a8aaa',
  },
  playerStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  abilityBadge: {
    backgroundColor: '#1a4a3c',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
  },
  abilityText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#00ff88',
  },
  playerValue: {
    fontSize: 10,
    color: '#6a8aaa',
    minWidth: 42,
    textAlign: 'right',
  },
  playerNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  positionBadge: {
    backgroundColor: '#1a4a6c',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 3,
  },
  positionBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#4a9eff',
  },
  currentFormationCard: {
    backgroundColor: '#0d2137',
    padding: 32,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#1a4a6c',
    alignItems: 'center',
  },
  currentFormation: {
    fontSize: 48,
    fontWeight: '900',
    color: '#00ff88',
    marginTop: 12,
  },
  currentFormationLabel: {
    fontSize: 12,
    color: '#6a8aaa',
    marginTop: 8,
  },
  advancedTacticsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0d2137',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#00ff88',
  },
  advancedTacticsIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#1a4a3c',
    alignItems: 'center',
    justifyContent: 'center',
  },
  advancedTacticsInfo: {
    flex: 1,
    marginLeft: 16,
  },
  advancedTacticsTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
  },
  advancedTacticsDescription: {
    fontSize: 12,
    color: '#6a8aaa',
    marginTop: 4,
  },
  advancedTacticsTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  advancedTacticsTag: {
    backgroundColor: '#1a4a3c',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  advancedTacticsTagText: {
    fontSize: 9,
    color: '#00ff88',
    fontWeight: '600',
  },
  featureCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0d2137',
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1a4a6c',
    marginBottom: 8,
  },
  featureInfo: {
    flex: 1,
    marginLeft: 12,
  },
  featureTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  featureDescription: {
    fontSize: 11,
    color: '#6a8aaa',
    marginTop: 2,
  },
  leagueToggle: {
    flexDirection: 'row',
    backgroundColor: '#0d2137',
    borderRadius: 8,
    padding: 4,
    marginBottom: 16,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 6,
  },
  toggleButtonActive: {
    backgroundColor: '#1a4a6c',
  },
  toggleText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6a8aaa',
    letterSpacing: 1,
  },
  toggleTextActive: {
    color: '#fff',
  },
  fullTable: {
    backgroundColor: '#0d2137',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1a4a6c',
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    padding: 10,
    backgroundColor: '#1a3a5c',
  },
  tableHeaderText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#6a8aaa',
    width: 24,
    textAlign: 'center',
  },
  tablePosCol: {
    width: 24,
  },
  tableTeamCol: {
    flex: 1,
    textAlign: 'left',
  },
  tablePtsCol: {
    width: 30,
  },
  tableDataRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#1a3a5c',
  },
  tableData: {
    fontSize: 10,
    color: '#9ab8d8',
    width: 24,
    textAlign: 'center',
  },
  weekSection: {
    marginBottom: 12,
  },
  weekTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4a9eff',
    marginBottom: 6,
  },
  fixtureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0d2137',
    padding: 8,
    borderRadius: 4,
    marginBottom: 3,
  },
  fixtureRowHighlight: {
    backgroundColor: '#1a4a3c',
  },
  fixtureTeam: {
    flex: 1,
    fontSize: 10,
    color: '#9ab8d8',
  },
  fixtureTeamButton: {
    flex: 1,
    paddingVertical: 3,
  },
  fixtureScore: {
    paddingHorizontal: 10,
  },
  fixtureScoreText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#fff',
  },
  fixtureVs: {
    fontSize: 9,
    color: '#4a6a8a',
  },
  budgetDisplay: {
    backgroundColor: '#1a4a3c',
    padding: 12,
    borderRadius: 6,
    alignItems: 'center',
    marginBottom: 14,
  },
  budgetLabel: {
    fontSize: 10,
    color: '#6a8aaa',
    marginBottom: 3,
  },
  budgetValue: {
    fontSize: 24,
    fontWeight: '800',
    color: '#00ff88',
  },
  transferCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#0d2137',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1a4a6c',
    marginBottom: 8,
  },
  transferInfo: {
    flex: 1,
    marginRight: 12,
  },
  transferName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  transferMeta: {
    fontSize: 11,
    color: '#6a8aaa',
    marginTop: 2,
  },
  transferStats: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  transferStat: {
    fontSize: 9,
    color: '#4a9eff',
    fontWeight: '600',
  },
  transferAction: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 8,
  },
  transferPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: '#00ff88',
  },
  offerButton: {
    backgroundColor: '#4a9eff',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
  },
  offerButtonText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#fff',
  },
  searchSection: {
    marginBottom: 16,
  },
  searchRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  searchInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0d2137',
    borderWidth: 1,
    borderColor: '#1a4a6c',
    borderRadius: 8,
    paddingHorizontal: 12,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    color: '#fff',
    fontSize: 13,
  },
  positionFilterScroll: {
    flexGrow: 0,
  },
  positionFilterContent: {
    gap: 6,
    paddingRight: 16,
  },
  positionChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: '#0d2137',
    borderWidth: 1,
    borderColor: '#1a4a6c',
  },
  positionChipActive: {
    backgroundColor: '#1a4a3c',
    borderColor: '#00ff88',
  },
  positionChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6a8aaa',
  },
  positionChipTextActive: {
    color: '#00ff88',
  },
  noResults: {
    alignItems: 'center',
    padding: 32,
    backgroundColor: '#0d2137',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1a4a6c',
  },
  noResultsText: {
    color: '#6a8aaa',
    fontSize: 14,
    marginTop: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'flex-end',
  },
  transferOfferModal: {
    backgroundColor: '#0d2137',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 32,
    maxHeight: '75%',
  },
  transferOfferHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#1a4a6c',
  },
  transferOfferTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: 2,
  },
  transferOfferPlayerInfo: {
    padding: 20,
    backgroundColor: '#0a1628',
    borderBottomWidth: 1,
    borderBottomColor: '#1a3a5c',
  },
  transferOfferPlayerName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#00ff88',
    marginBottom: 6,
  },
  transferOfferPlayerMeta: {
    fontSize: 12,
    color: '#6a8aaa',
    marginBottom: 8,
  },
  transferOfferAskingPrice: {
    fontSize: 14,
    color: '#4a9eff',
    fontWeight: '600',
  },
  transferOfferSection: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1a3a5c',
  },
  transferOfferSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6a8aaa',
    letterSpacing: 1,
    marginBottom: 12,
  },
  transferFeeInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0a1628',
    padding: 16,
    borderRadius: 12,
    gap: 12,
  },
  transferFeePrefix: {
    fontSize: 24,
    fontWeight: '700',
    color: '#4a9eff',
  },
  transferFeeButton: {
    padding: 4,
  },
  transferFeeValueContainer: {
    alignItems: 'center',
    minWidth: 140,
  },
  transferFeeInput: {
    fontSize: 32,
    fontWeight: '900',
    color: '#fff',
    textAlign: 'center',
    minWidth: 140,
    padding: 0,
  },
  transferFeePresets: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  transferFeePresetButton: {
    flex: 1,
    paddingVertical: 8,
    backgroundColor: '#1a3a5c',
    borderRadius: 6,
    alignItems: 'center',
  },
  transferFeePresetText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4a9eff',
  },
  wageInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0a1628',
    padding: 16,
    borderRadius: 12,
    gap: 12,
  },
  wageInputPrefix: {
    fontSize: 24,
    fontWeight: '700',
    color: '#4a9eff',
  },
  wageButton: {
    padding: 4,
  },
  wageValueContainer: {
    alignItems: 'center',
    minWidth: 120,
  },
  wageInput: {
    fontSize: 32,
    fontWeight: '900',
    color: '#fff',
    textAlign: 'center',
    minWidth: 120,
    padding: 0,
  },
  wageValueLabel: {
    fontSize: 10,
    color: '#6a8aaa',
    marginTop: 2,
  },
  wagePresets: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  wagePresetButton: {
    flex: 1,
    paddingVertical: 8,
    backgroundColor: '#1a3a5c',
    borderRadius: 6,
    alignItems: 'center',
  },
  wagePresetText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4a9eff',
  },
  transferOfferInfo: {
    marginTop: 16,
    padding: 12,
    backgroundColor: '#0a1628',
    borderRadius: 8,
    gap: 8,
  },
  transferOfferInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  transferOfferInfoLabel: {
    fontSize: 12,
    color: '#6a8aaa',
  },
  transferOfferInfoValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  submitOfferButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00ff88',
    marginHorizontal: 20,
    marginTop: 16,
    paddingVertical: 16,
    borderRadius: 8,
    gap: 8,
  },
  submitOfferButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0a1628',
    letterSpacing: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
  },
  loadingText: {
    fontSize: 16,
    color: '#6a8aaa',
    fontWeight: '600',
  },
  formationGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  formationButton: {
    backgroundColor: '#0d2137',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#1a4a6c',
  },
  formationButtonActive: {
    borderColor: '#00ff88',
    backgroundColor: '#1a4a3c',
  },
  formationText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#6a8aaa',
  },
  formationTextActive: {
    color: '#00ff88',
  },
  // Friendly Scheduler Button styles
  friendlySchedulerButton: {
    backgroundColor: '#0d2137',
    borderRadius: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: '#ffd700',
  },
  friendlyButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  friendlyButtonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  friendlyButtonText: {
    gap: 4,
  },
  friendlyButtonTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#ffd700',
    letterSpacing: 0.5,
  },
  friendlyButtonSubtitle: {
    fontSize: 12,
    color: '#6a8aaa',
  },
});
