import { StyleSheet } from 'react-native';

export const matchStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a1628',
  },
  noMatchContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  noMatchText: {
    fontSize: 18,
    color: '#6a8aaa',
  },
  backButton: {
    backgroundColor: '#1a4a6c',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 16,
  },
  backButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  // Scoreboard
  scoreboard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#0d2137',
    borderBottomWidth: 2,
    borderBottomColor: '#1a4a6c',
  },
  scoreboardTeam: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  scoreboardTeamName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#9ab8d8',
    flex: 1,
  },
  scoreboardTeamHighlight: {
    color: '#00ff88',
  },
  scoreboardScore: {
    fontSize: 32,
    fontWeight: '900',
    color: '#fff',
    minWidth: 40,
    textAlign: 'center',
  },
  scoreboardCenter: {
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  minuteContainer: {
    alignItems: 'center',
  },
  minuteText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#00ff88',
  },
  pausedText: {
    fontSize: 10,
    color: '#ff6b6b',
    fontWeight: '700',
    marginTop: 2,
  },
  fullTimeLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#4a9eff',
  },
  vsText: {
    fontSize: 14,
    color: '#4a6a8a',
    fontWeight: '600',
  },
  // Formation comparison bar
  formationBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#0d1a28',
    borderBottomWidth: 1,
    borderBottomColor: '#1a3a5c',
  },
  formationTeam: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  formationText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#9ab8d8',
  },
  formationVs: {
    fontSize: 10,
    color: '#4a6a8a',
    fontWeight: '600',
  },
  // Tab bar
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#0d2137',
    borderBottomWidth: 2,
    borderBottomColor: '#1a4a6c',
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 6,
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  tabActive: {
    borderBottomColor: '#00ff88',
  },
  tabText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6a8aaa',
  },
  tabTextActive: {
    color: '#00ff88',
  },
  // Pause controls
  pauseControls: {
    flexDirection: 'row',
    padding: 12,
    gap: 8,
    backgroundColor: '#0d1a28',
    borderBottomWidth: 1,
    borderBottomColor: '#1a3a5c',
  },
  pauseControlButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0d2137',
    paddingVertical: 12,
    borderRadius: 8,
    gap: 6,
    borderWidth: 1,
    borderColor: '#1a4a6c',
  },
  resumeButton: {
    backgroundColor: '#00ff88',
    borderColor: '#00ff88',
  },
  pauseControlText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
  },
  speedControls: {
    padding: 16,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#1a3a5c',
  },
  speedLabel: {
    fontSize: 12,
    color: '#6a8aaa',
    marginBottom: 12,
  },
  speedButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  speedButton: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 6,
    backgroundColor: '#0d2137',
    borderWidth: 1,
    borderColor: '#1a4a6c',
  },
  speedButtonActive: {
    backgroundColor: '#00ff88',
    borderColor: '#00ff88',
  },
  speedButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#6a8aaa',
  },
  speedButtonTextActive: {
    color: '#0a1628',
  },
  contentContainer: {
    flex: 1,
  },
  tabContent: {
    flex: 1,
  },
  // Pre-match
  preMatchContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    gap: 12,
  },
  preMatchTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 3,
  },
  preMatchSubtitle: {
    fontSize: 14,
    color: '#4a9eff',
  },
  preMatchInfo: {
    fontSize: 12,
    color: '#6a8aaa',
    marginTop: 8,
  },
  preMatchFormations: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    marginTop: 16,
  },
  preMatchFormationItem: {
    alignItems: 'center',
  },
  preMatchFormationTeam: {
    fontSize: 12,
    color: '#6a8aaa',
    marginBottom: 4,
  },
  preMatchFormationValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#4a9eff',
  },
  preMatchFormationVs: {
    fontSize: 16,
    color: '#4a6a8a',
    fontWeight: '600',
  },
  startButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#00ff88',
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 8,
    gap: 12,
    marginTop: 24,
  },
  startButtonText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0a1628',
    letterSpacing: 2,
  },
  // Pitch view
  pitchViewContainer: {
    alignItems: 'center',
    padding: 16,
  },
  miniPitchContainer: {
    position: 'relative',
    backgroundColor: '#0d2137',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#1a4a6c',
    overflow: 'hidden',
    marginBottom: 20,
  },
  miniPitch: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1a5a3f',
    position: 'relative',
  },
  centerLine: {
    position: 'absolute',
    width: '100%',
    height: 2,
    backgroundColor: '#ffffff',
    opacity: 0.4,
  },
  centerCircle: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#ffffff',
    opacity: 0.4,
  },
  penaltyBox: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#ffffff',
    opacity: 0.4,
  },
  penaltyBoxTop: {
    top: 0,
  },
  penaltyBoxBottom: {
    bottom: 0,
  },
  miniPlayerDot: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  homePlayerDot: {
    backgroundColor: '#4a9eff',
  },
  awayPlayerDot: {
    backgroundColor: '#ff9f43',
  },
  miniPlayerLabel: {
    fontSize: 7,
    fontWeight: '800',
    color: '#fff',
  },
  homePlayerLabel: {
    color: '#fff',
  },
  awayPlayerLabel: {
    color: '#fff',
  },
  ballIndicator: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ffcc00',
    alignItems: 'center',
    justifyContent: 'center',
  },
  latestEventCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0d2137',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#1a4a6c',
    width: '100%',
  },
  latestEventIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  latestEventContent: {
    flex: 1,
  },
  latestEventMinute: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4a9eff',
    marginBottom: 2,
  },
  latestEventTeam: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6a8aaa',
    marginBottom: 4,
  },
  latestEventDescription: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  // Commentary view
  commentaryContent: {
    padding: 16,
    paddingBottom: 100,
  },
  kickoffEvent: {
    backgroundColor: '#1a4a3c',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 16,
  },
  kickoffText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#00ff88',
    letterSpacing: 2,
  },
  eventItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
    backgroundColor: '#0d2137',
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
  },
  eventMinute: {
    width: 36,
  },
  eventMinuteText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4a9eff',
  },
  eventIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  eventContent: {
    flex: 1,
  },
  eventTeam: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6a8aaa',
    marginBottom: 2,
  },
  eventDescription: {
    fontSize: 13,
    color: '#fff',
    lineHeight: 18,
  },
  fullTimeEvent: {
    backgroundColor: '#1a3a5c',
    padding: 24,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 16,
  },
  fullTimeText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 3,
  },
  finalScore: {
    fontSize: 32,
    fontWeight: '900',
    color: '#00ff88',
    marginTop: 8,
  },
  // Stats view
  statsContainer: {
    padding: 16,
  },
  statItem: {
    marginBottom: 24,
  },
  statHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6a8aaa',
    letterSpacing: 1,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '900',
    color: '#fff',
  },
  statBarContainer: {
    flexDirection: 'row',
    height: 8,
    backgroundColor: '#1a3a5c',
    borderRadius: 4,
    overflow: 'hidden',
  },
  statBar: {
    height: '100%',
  },
  homeStatBar: {
    backgroundColor: '#4a9eff',
  },
  awayStatBar: {
    backgroundColor: '#ff9f43',
  },
  // Footer
  liveFooter: {
    padding: 16,
    backgroundColor: '#0d2137',
    borderTopWidth: 1,
    borderTopColor: '#1a4a6c',
    gap: 12,
  },
  liveControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pauseButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ff6b6b',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 6,
    gap: 6,
  },
  pauseButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
  },
  progressBar: {
    width: '100%',
    height: 4,
    backgroundColor: '#1a3a5c',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#00ff88',
  },
  postFooter: {
    padding: 16,
    backgroundColor: '#0d2137',
    borderTopWidth: 1,
    borderTopColor: '#1a4a6c',
  },
  finishButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00ff88',
    paddingVertical: 16,
    borderRadius: 8,
    gap: 8,
  },
  finishButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0a1628',
    letterSpacing: 1,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#0d2137',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: 2,
  },
  modalSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6a8aaa',
    marginBottom: 12,
  },
  formationGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  formationOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#0a1628',
    borderWidth: 2,
    borderColor: '#1a4a6c',
  },
  formationOptionActive: {
    borderColor: '#00ff88',
    backgroundColor: '#1a4a3c',
  },
  formationOptionText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#6a8aaa',
  },
  formationOptionTextActive: {
    color: '#00ff88',
  },
  subsList: {
    maxHeight: 300,
  },
  subsListTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4a9eff',
    marginBottom: 8,
  },
  subPlayerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0a1628',
    padding: 12,
    borderRadius: 6,
    marginBottom: 6,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  subPlayerRowSelected: {
    borderColor: '#ff6b6b',
    backgroundColor: '#2a1628',
  },
  subPlayerInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  subPlayerPosition: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4a9eff',
    width: 30,
  },
  subPlayerName: {
    fontSize: 13,
    color: '#fff',
    flex: 1,
  },
  subPlayerAbility: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6a8aaa',
  },
  subButton: {
    padding: 8,
  },
  subAbility: {
    backgroundColor: '#1a4a3c',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  subAbilityText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#00ff88',
  },
  subsNote: {
    fontSize: 11,
    color: '#4a6a8a',
    textAlign: 'center',
    marginVertical: 12,
    fontStyle: 'italic',
  },
  modalCloseButton: {
    backgroundColor: '#00ff88',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalCloseButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0a1628',
    letterSpacing: 1,
  },
  selectTeamButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4a9eff',
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 8,
    gap: 12,
    marginTop: 24,
  },
  selectTeamButtonText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0a1628',
    letterSpacing: 2,
  },
  lineupConfirmedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a4a3c',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    gap: 8,
    marginTop: 16,
  },
  lineupConfirmedText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#00ff88',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
  },
  loadingText: {
    fontSize: 16,
    color: '#6a8aaa',
    fontWeight: '600',
  },
  // Swap indicator styles
  swapIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1a4a3c',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 12,
    gap: 8,
  },
  swapIndicatorText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#00ff88',
  },
  lineupNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1a3a5c',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  lineupNumberText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6a8aaa',
  },
  // Phase 2 Styles
  momentumSection: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#1a3a5c',
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#00ff88',
    letterSpacing: 1,
    marginBottom: 12,
    textAlign: 'center',
  },
  momentumBar: {
    marginBottom: 12,
  },
  momentumLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  momentumLabelHome: {
    fontSize: 11,
    fontWeight: '600',
    color: '#4a9eff',
  },
  momentumLabelAway: {
    fontSize: 11,
    fontWeight: '600',
    color: '#ff6b6b',
  },
  momentumBarTrack: {
    height: 6,
    backgroundColor: '#0d2137',
    borderRadius: 3,
    marginBottom: 4,
    overflow: 'hidden',
  },
  momentumBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  momentumTimeline: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 4,
    marginTop: 8,
  },
  momentumPoint: {
    alignItems: 'center',
    gap: 2,
  },
  momentumDotHome: {
    width: 4,
    backgroundColor: '#4a9eff',
    borderRadius: 2,
  },
  momentumMinute: {
    fontSize: 8,
    color: '#4a6a8a',
  },
  momentumDotAway: {
    width: 4,
    backgroundColor: '#ff6b6b',
    borderRadius: 2,
  },
  ratingsSection: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#1a3a5c',
  },
  ratingsTeamName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#8ab4d8',
    marginBottom: 8,
    marginTop: 4,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#0d213720',
  },
  ratingPosition: {
    fontSize: 10,
    fontWeight: '700',
    color: '#6a8aaa',
    width: 28,
    textAlign: 'center',
  },
  ratingPlayerName: {
    flex: 1,
    fontSize: 12,
    color: '#d0e8ff',
    marginLeft: 8,
  },
  ratingBadge: {
    width: 36,
    height: 24,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ratingValue: {
    fontSize: 12,
    fontWeight: '800',
  },
  // Week Simulation Loading Screen
  simLoadingOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 10, 20, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  simLoadingContainer: {
    width: '85%',
    maxWidth: 360,
  },
  simLoadingScreen: {
    backgroundColor: '#0a1628',
    borderWidth: 2,
    borderColor: '#00ff88',
    borderRadius: 8,
    padding: 24,
    alignItems: 'center',
    // Retro CRT glow effect
    shadowColor: '#00ff88',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  simLoadingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  simLoadingTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#00ff88',
    letterSpacing: 2,
  },
  simLoadingWeek: {
    fontSize: 20,
    fontWeight: '700',
    color: '#d0e8ff',
    marginBottom: 20,
  },
  simLoadingDots: {
    marginBottom: 20,
  },
  simLoadingDotsText: {
    fontSize: 13,
    color: '#6a8aaa',
    fontStyle: 'italic',
    letterSpacing: 1,
  },
  simProgressContainer: {
    width: '100%',
    alignItems: 'center',
  },
  simProgressTrack: {
    width: '100%',
    height: 8,
    backgroundColor: '#0d2137',
    borderRadius: 4,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#1a3a5c',
  },
  simProgressFill: {
    height: '100%',
    backgroundColor: '#00ff88',
    borderRadius: 3,
  },
  simProgressText: {
    marginTop: 8,
    fontSize: 11,
    color: '#4a6a8a',
    letterSpacing: 1,
  },
  simLoadingFooter: {
    marginTop: 20,
    fontSize: 11,
    color: '#3a5a7a',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  
  // Live Match Control Bar
  liveControlBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0d2137',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#1a4a6c',
    gap: 8,
  },
  liveControlButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1a4a6c',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  liveMenuButton: {
    backgroundColor: '#0d2137',
    borderWidth: 1,
    borderColor: '#00ff88',
  },
  liveControlText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
  },
  liveSpeedControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
    justifyContent: 'center',
  },
  liveSpeedLabel: {
    color: '#6a8aaa',
    fontSize: 10,
    fontWeight: '600',
  },
  liveSpeedButton: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 4,
    backgroundColor: '#1a3a5c',
  },
  liveSpeedButtonActive: {
    backgroundColor: '#00ff88',
  },
  liveSpeedText: {
    color: '#6a8aaa',
    fontSize: 11,
    fontWeight: '700',
  },
  liveSpeedTextActive: {
    color: '#0a1628',
  },
});

